version: '3.8'

services:
  go-app:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

  nextjs-app:
    build:
      context: ./inc42-website-nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  wordpress-app:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html/wp-content
    networks:
      - my-network

networks:
  my-network:

volumes:
  wordpress-data:
