name: Build and Push Next.js Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'inc42-website-nextjs/**'

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'  # Adjust based on your Node version

      # - name: Install dependencies
      #   run: npm install

      # - name: Run ESLint
      #   run: npm run lint

      # - name: Run Prettier
      #   run: npm run format:check      

      - name: Build the Next.js Docker image
        run: docker build ./inc42-website-nextjs -t sidwar/nextjs:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push the Next.js Docker image
        run: docker push sidwar/nextjs:latest
